### ISSUE TITLE
Issue with relative paths.

### ISSUE THREAD

**Issue by satazor** [frozzare/wp-test-suite#1]
Thanks for this library, it really made it easier to setup wordpress plugin tests.

I've hit an issue with the current `install-wp-tests.php` on these lines https://github.com/frozzare/wp-test-suite/blob/master/bin/install-wp-tests.sh#L84 and https://github.com/frozzare/wp-test-suite/blob/master/bin/install-wp-tests.sh#L86 when using relative paths. If I remove the first line and change the second line to `if [ ! -f "$WP_TESTS_DIR/wp-tests-config.php" ]; then` it works.

Besides that, it's working flawlessly.

Btw, I see that you are requiring an old version of phpunit. Do you mind updating to `~5.6` which is the latest sable release?

Thank you.

**Comment by frozzare** [comment]
Thanks for your issue, glad you like the project.

Upgrading to latest phpunit will break support for old php versions, so that isn't a good idea.
