### ISSUE TITLE
Path error on latest VVV?

### ISSUE THREAD

**Issue by Lindstromer** [frozzare/wp-test-suite#2]
There seems to be an error on the latest VVV-machine when you try to run the tests. Narrowed it down to being a problem with VVV using "public_html"-folders, which I'm guessing is a new thing.

Changed the following in _class-wp-test-suite.php_ to make it work:
```
if ( file_exists( '/srv/www/wordpress-develop/tests/phpunit/includes/bootstrap.php' ) ) {
	return '/srv/www/wordpress-develop/tests/phpunit';
}
```
Into:
```
if ( file_exists( '/srv/www/wordpress-develop/public_html/tests/phpunit/includes/bootstrap.php' ) ) {
	return '/srv/www/wordpress-develop/public_html/tests/phpunit';
}
```

If you'd like I could make an pull request, but I'm not sure wether it's a problem for others with VVV-setups or not, at the moment.

**Comment by Lindstromer** [comment]
Also not sure if it's supposed to match VVV-folder structure, but it does look like it is. ;)

**Comment by frozzare** [comment]
You could do a PR adding this so it don't break old VVV's.
